"""Maintainer export inventory and upstream-source audit (no installation)."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tarfile

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATHS = [
    "src-tauri/src/native_klayout.rs",
    "src-tauri/src/native_klayout_package.rs",
    "src-tauri/src/native_klayout_linux.py",
    "scripts/klayout-linux-package.test.py",
    "packaging/extensions/klayout/0.30.12.json",
    "packages/dds-editor/src/lib/ide/klayoutExtension.ts",
    *["src-tauri/permissions/autogenerated/" + command + "_klayout_extension.toml"
      for command in ("read", "prepare", "change", "cancel", "open")],
]
COMMIT = "e71272c3b178105bd2a2f25af54673a7af7ed60d"
ARCHIVE_SHA256 = "fa747d9a4c216d0645587e05df365d5c22f73609ab98b34471372c711d8c2b75"
ARCHIVE_BYTES = 104078293


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main(dds_root):
    files = []
    for name in SOURCE_PATHS:
        data = (ROOT / name).read_bytes()
        if data != (dds_root / name).read_bytes():
            raise ValueError("DDS source equality check failed: " + name)
        files.append({"path": name, "ddsPath": name, "sha256": digest(data), "sizeBytes": len(data), "license": "Apache-2.0"})
    commit = subprocess.check_output(["git", "-C", str(dds_root), "rev-parse", "HEAD"], text=True).strip()
    inventory = {"schema": "dds.public-integration-source-inventory.v1", "integrationId": "org.klayout.viewer",
                 "viewerVersion": "0.30.12", "ddsSourceCommit": commit,
                 "exportMode": "selected integration-specific files copied byte-for-byte; no host/UI/services tree export",
                 "files": files}
    (ROOT / "source-inventory.json").write_text(json.dumps(inventory, indent=2) + "\n")
    archive_path = ROOT / "dist/upstream/klayout-0.30.12.tar.gz"
    archive_data = archive_path.read_bytes()
    if len(archive_data) != ARCHIVE_BYTES or digest(archive_data) != ARCHIVE_SHA256:
        raise ValueError("upstream archive integrity mismatch")
    notices = []
    dependency_notices = ["COPYRIGHT", "LICENSE", "CONTRIB", "macbuild/LICENSE",
                          "src/plugins/streamers/lstream/runtime/capnp/LICENSE", "src/plugins/streamers/lstream/runtime/kj/LICENSE"]
    with tarfile.open(archive_path) as archive:
        version = archive.extractfile("klayout-0.30.12/version.sh").read()
        if b'KLAYOUT_VERSION="0.30.12"' not in version:
            raise ValueError("upstream archive version mismatch")
        for name in dependency_notices:
            data = archive.extractfile("klayout-0.30.12/" + name).read()
            target = ROOT / "licenses/source" / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            notices.append({"path": target.relative_to(ROOT).as_posix(), "archivePath": "klayout-0.30.12/" + name,
                            "sha256": digest(data), "sizeBytes": len(data)})
    for name, path in [("COPYRIGHT", "licenses/KLayout-COPYRIGHT"), ("LICENSE", "licenses/KLayout-LICENSE")]:
        data = (ROOT / path).read_bytes()
        notices.append({"path": path, "url": f"https://raw.githubusercontent.com/KLayout/klayout/{COMMIT}/{name}",
                        "sha256": digest(data), "sizeBytes": len(data)})
    upstream = {"schema": "dds.klayout-upstream-source.v1", "name": "KLayout", "version": "0.30.12",
                "license": "GPL-3.0-or-later", "tag": "v0.30.12", "commit": COMMIT,
                "repository": "https://github.com/KLayout/klayout", "release": "https://github.com/KLayout/klayout/releases/tag/v0.30.12",
                "sourceArchive": {"url": "https://www.klayout.org/downloads/source/klayout-0.30.12.tar.gz",
                                  "releaseAssetName": "klayout-0.30.12.tar.gz", "sha256": ARCHIVE_SHA256,
                                  "sizeBytes": ARCHIVE_BYTES, "localPath": "dist/upstream/klayout-0.30.12.tar.gz"},
                "sourceArchiveAudit": {"downloaded": True, "hashVerified": True, "versionFileVerified": True,
                                       "built": False, "executedOrInstalled": False,
                                       "modified": False, "archiveContainsBuildScripts": ["build.sh", "build.bat", "build4mac.py", "setup.py"]},
                "notices": notices}
    (ROOT / "upstream-source.json").write_text(json.dumps(upstream, indent=2) + "\n")
    print(f"Inventoried {len(files)} exact DDS files and {len(notices)} unchanged upstream notices")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dds_root", type=Path)
    main(parser.parse_args().dds_root)
